---
- name: install subscription-manager
  hosts: all

  tasks:
    - name: Create temp repo
      shell: |
        if [ ! -f "/etc/yum.repos.d/temp.repo" ]
        then
          cd /etc/yum.repos.d/
          touch temp.repo
          echo "[software_linux74]" >> temp.repo
          echo "name = rhel74" >> temp.repo
          echo "baseurl = http://10.245.218.89/software/rhel74" >> temp.repo
          echo "enabled = 1" >> temp.repo
        fi

    - name: install subscription-manager
      yum: name=subscription-manager state=latest

    - name: delete temp repo
      command: rm /etc/yum.repos.d/temp.repo
