---
- name: subscription-manager
  hosts: all

  tasks:
   -name: test
    shell: |
      cd /tmp
      touch testme
#   - name: install subscription-manager
#     yum: name=subscription-manager state=latest
